### ISSUE TITLE
Set Up the Chartly Repository

### ISSUE THREAD

**Issue by Azendae-Popo** [ec-intl/chartly#1]
## Purpose

Set up the `plotting` repository so that it complies with company standards and Python Packaging Projects Standards.

```[tasklist]
### Tasks
- [x] Move Visualization.py into plotting repo
- [x] Update the README with descriptions about this package and its uses
- [x] Update the docstrings on all functions
- [x] https://github.com/ec-intl/chartly/issues/4
- [x] build sphinx docs
```
