### ISSUE TITLE
Add ScatterPlot

### ISSUE THREAD

**Issue by Azendae-Popo** [ec-intl/chartly#23]
## Purpose
Add ScatterPlot chart to chartly

1. Update the line plot with markers option
2. Add Scatterplot chart
3. Update Docs with new chart demonstration

```[tasklist]
### Tasks
- [x] Update the line plot chart customizations
- [x] Add Scatterplot chart
- [x] Update Plot.rst with Scatterplot Demo
```

**Comment by Azendae-Popo** [comment]
Completed 🌵
